
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RSTRING = 43;
  public static final int RTRUE = 51;
  public static final int MULT = 12;
  public static final int CONST = 44;
  public static final int CHAR = 42;
  public static final int IGUALA = 26;
  public static final int ENTERO = 3;
  public static final int XOR = 34;
  public static final int CONTINUE = 54;
  public static final int INT = 39;
  public static final int DOSPT = 22;
  public static final int RFALSE = 52;
  public static final int FOR = 49;
  public static final int LLAVIZQ = 16;
  public static final int MATCH = 47;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int MAYORQUE = 31;
  public static final int IGUAL = 25;
  public static final int CORDER = 19;
  public static final int OR = 32;
  public static final int BOOL = 41;
  public static final int RDOUBLE = 40;
  public static final int DIV = 13;
  public static final int IF = 45;
  public static final int UMENOS = 11;
  public static final int ID = 5;
  public static final int DECRE = 24;
  public static final int EOF = 0;
  public static final int PARIZQ = 20;
  public static final int DECIMAL = 4;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 15;
  public static final int MENOS = 10;
  public static final int MENOR = 28;
  public static final int BREAK = 53;
  public static final int MENORQUE = 29;
  public static final int MAYOR = 30;
  public static final int POTENCIA = 14;
  public static final int LLAVDER = 17;
  public static final int FLECHA = 36;
  public static final int ELSE = 46;
  public static final int WHILE = 48;
  public static final int DEFAULT = 37;
  public static final int INCRE = 23;
  public static final int PTCOMA = 7;
  public static final int DIFER = 27;
  public static final int PARDER = 21;
  public static final int CORIZQ = 18;
  public static final int CARAC = 6;
  public static final int VAR = 38;
  public static final int DO = 50;
  public static final int PRINT = 8;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CARAC",
  "PTCOMA",
  "PRINT",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULT",
  "DIV",
  "POTENCIA",
  "MODULO",
  "LLAVIZQ",
  "LLAVDER",
  "CORIZQ",
  "CORDER",
  "PARIZQ",
  "PARDER",
  "DOSPT",
  "INCRE",
  "DECRE",
  "IGUAL",
  "IGUALA",
  "DIFER",
  "MENOR",
  "MENORQUE",
  "MAYOR",
  "MAYORQUE",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "FLECHA",
  "DEFAULT",
  "VAR",
  "INT",
  "RDOUBLE",
  "BOOL",
  "CHAR",
  "RSTRING",
  "CONST",
  "IF",
  "ELSE",
  "MATCH",
  "WHILE",
  "FOR",
  "DO",
  "RTRUE",
  "RFALSE",
  "BREAK",
  "CONTINUE"
  };
}

